### ISSUE TITLE
make check failed in fjcontrib@1.045

### ISSUE THREAD

**Issue by Tom-python0121** [fjcontrib/fjcontrib#1]
I meet a problem:make check failed in fjcontrib@1.045
### Steps to reproduce the issue

```console
[root@centos8 ~]# spack install --keep-stage -v fjcontrib@1.045\
[root@centos8 ~]# spack cd fjcontrib@1.045
[root@centos8 spack-src]# spack load fjcontrib
[root@centos8 spack-src]# . ../spack-build-env.txt
[root@centos8 spack-src]# make -j16 check
Summary of tests
----------------
  Centauro             example                   Success
  ClusteringVetoPlugin example                   Success
  SoftKiller           example                   Success
  ScJet                example                   Success
  LundPlane            example                   Success
  LundPlane            example_secondary         Success
  JetFFMoments         example                   Success
  QCDAwarePlugin       example                   Success
  ValenciaPlugin       example                   Success
  FlavorCone           example                   Success
  VariableR            example                   Success
  SubjetCounting       example                   Success
  ConstituentSubtractor example_jet_by_jet        Success
  ConstituentSubtractor example_event_wide        Success
  ConstituentSubtractor example_iterative         Success
  ConstituentSubtractor example_background_rescaling Failed (see difference file)
  ConstituentSubtractor example_whole_event_using_charged_info Failed (see difference file)
  JetsWithoutJets      example_basic_usage       Success
  JetsWithoutJets      example_advanced_usage    Success
  EnergyCorrelator     example                   Failed (see difference file)
  EnergyCorrelator     example_basic_usage       Success
  JetCleanser          example                   Success
  GenericSubtractor    example                   Success
  GenericSubtractor    example_with_components   Success
  RecursiveTools       example_mmdt              Success
  RecursiveTools       example_mmdt_sub          Success
  RecursiveTools       example_mmdt_ee           Success
  RecursiveTools       example_recluster         Success
  RecursiveTools       example_softdrop          Success
  RecursiveTools       example_advanced_usage    Success
  RecursiveTools       example_recursive_softdrop Failed (see difference file)
  RecursiveTools       example_bottomup_softdrop Success
  RecursiveTools       example_isd               Success
  Nsubjettiness        example_basic_usage       Success
  Nsubjettiness        example_advanced_usage    Success
  Nsubjettiness        example_v1p0p3            Success
  Nsubjettiness        example_advanced_usage_ee Failed (see difference file)

32 out of 37 tests passed

In directory ConstituentSubtractor/ checking the output of 'example_background_rescaling' using the input file
../data/Pythia-Zp2jets-lhc-pileup-1ev.dat and reference file example_background_rescaling.ref
ERROR: Outputs differ (output, stderr and diff available in
       example_background_rescaling.tmp_ref , example_background_rescaling.tmp_err and example_background_rescaling.diff)


In directory ConstituentSubtractor/ checking the output of 'example_whole_event_using_charged_info' using the input file
../data/Pythia-Zp2jets-lhc-pileup-1ev.dat and reference file example_whole_event_using_charged_info.ref
g++ -o example_basic_usage example_basic_usage.o -L. -lJetsWithoutJets -lm -Wl,-rpath,/home/spack/spack/opt/spack/linux-centos8-aarch64/gcc-8.4.1/fastjet-3.3.3-hm2yxti4u6lk3svbhoezwq5cbfmxeevx/lib -L/home/spack/spack/opt/spack/linux-centos8-aarch64/gcc-8.4.1/fastjet-3.3.3-hm2yxti4u6lk3svbhoezwq5cbfmxeevx/lib -lfastjettools -lfastjet -lm
ERROR: Outputs differ (output, stderr and diff available in
       example_whole_event_using_charged_info.tmp_ref , example_whole_event_using_charged_info.tmp_err and example_whole_event_using_charged_info.diff)

make[1]: Leaving directory '/tmp/root/spack-stage/spack-stage-fjcontrib-1.045-p3757gwycatauhvqg2vtcbbx5fmlgvwv/spack-src/ConstituentSubtractor'
g++ -o example_advanced_usage example_advanced_usage.o -L. -lJetsWithoutJets -lm -Wl,-rpath,/home/spack/spack/opt/spack/linux-centos8-aarch64/gcc-8.4.1/fastjet-3.3.3-hm2yxti4u6lk3svbhoezwq5cbfmxeevx/lib -L/home/spack/spack/opt/spack/linux-centos8-aarch64/gcc-8.4.1/fastjet-3.3.3-hm2yxti4u6lk3svbhoezwq5cbfmxeevx/lib -lfastjettools -lfastjet -lm
g++ -O3 -Wall -g -I/home/spack/spack/opt/spack/linux-centos8-aarch64/gcc-8.4.1/fastjet-3.3.3-hm2yxti4u6lk3svbhoezwq5cbfmxeevx/include   -c -o example_recluster.o example_recluster.cc
g++ -O3 -Wall -Woverloaded-virtual -g -Wunused-parameter -I/home/spack/spack/opt/spack/linux-centos8-aarch64/gcc-8.4.1/fastjet-3.3.3-hm2yxti4u6lk3svbhoezwq5cbfmxeevx/include   -c -o example_v1p0p3.o example_v1p0p3.cc

In directory JetsWithoutJets/ checking the output of 'example_basic_usage' using the input file
../data/single-event.dat and reference file example_basic_usage.ref

In directory JetsWithoutJets/ checking the output of 'example_advanced_usage' using the input file
../data/single-event.dat and reference file example_advanced_usage.ref
g++ -O3 -Wall -g -I/home/spack/spack/opt/spack/linux-centos8-aarch64/gcc-8.4.1/fastjet-3.3.3-hm2yxti4u6lk3svbhoezwq5cbfmxeevx/include   -c -o example_softdrop.o example_softdrop.cc
ERROR: Outputs differ (output, stderr and diff available in
       example.tmp_ref , example.tmp_err and example.diff)

In directory RecursiveTools/ checking the output of 'example_recursive_softdrop' using the input file
../data/single-event.dat and reference file example_recursive_softdrop.ref
ERROR: Outputs differ (output, stderr and diff available in
       example_recursive_softdrop.tmp_ref , example_recursive_softdrop.tmp_err and example_recursive_softdrop.diff)

In directory Nsubjettiness/ checking the output of 'example_advanced_usage_ee' using the input file
../data/single-ee-event.dat and reference file example_advanced_usage_ee.ref
ERROR: Outputs differ (output, stderr and diff available in
       example_advanced_usage_ee.tmp_ref , example_advanced_usage_ee.tmp_err and example_advanced_usage_ee.diff)
```
Can you help me look at it?
### Information on your system
[root@centos8 spack-src]# spack debug report
* **Spack:** 0.16.1-1624-a0b5dcca3c
* **Python:** 3.6.8
* **Platform:** linux-centos8-aarch64
* **Concretizer:** original

**Comment by gavinsalam** [comment]
Dear Jeffrey,

I’ve just tried a build on a centos8 system (CERN’s lxplus8) using ***@***.*** with ***@***.*** without using spack and it went fine. (The spack fastjet, 3.3.3, is a bit old, but switching between 3.3.3 and 3.4.0 doesn’t change the outcome)

(I also tried using spack for the installation on a mac and didn’t run into any trouble)

Could you send us some output files, e.g. those from

ERROR: Outputs differ (output, stderr and diff available in
       example_background_rescaling.tmp_ref , example_background_rescaling.tmp_err and example_background_rescaling.diff)

to help us see what is going on? (And ideally tell us if you’re using the system default compiler)

Thanks,
Gavin

On 10 Jul 2021, at 08:56, Jeffrey ***@***.******@***.***>> wrote:



I meet a problem:make check failed in ***@***.***

Steps to reproduce the issue

***@***.*** ~]# spack install --keep-stage -v ***@***.***\
***@***.*** ~]# spack cd ***@***.***
***@***.*** spack-src]# spack load fjcontrib
***@***.*** spack-src]# . ../spack-build-env.txt
***@***.*** spack-src]# make -j16 check
Summary of tests
----------------
  Centauro             example                   Success
  ClusteringVetoPlugin example                   Success
  SoftKiller           example                   Success
  ScJet                example                   Success
  LundPlane            example                   Success
  LundPlane            example_secondary         Success
  JetFFMoments         example                   Success
  QCDAwarePlugin       example                   Success
  ValenciaPlugin       example                   Success
  FlavorCone           example                   Success
  VariableR            example                   Success
  SubjetCounting       example                   Success
  ConstituentSubtractor example_jet_by_jet        Success
  ConstituentSubtractor example_event_wide        Success
  ConstituentSubtractor example_iterative         Success
  ConstituentSubtractor example_background_rescaling Failed (see difference file)
  ConstituentSubtractor example_whole_event_using_charged_info Failed (see difference file)
  JetsWithoutJets      example_basic_usage       Success
  JetsWithoutJets      example_advanced_usage    Success
  EnergyCorrelator     example                   Failed (see difference file)
  EnergyCorrelator     example_basic_usage       Success
  JetCleanser          example                   Success
  GenericSubtractor    example                   Success
  GenericSubtractor    example_with_components   Success
  RecursiveTools       example_mmdt              Success
  RecursiveTools       example_mmdt_sub          Success
  RecursiveTools       example_mmdt_ee           Success
  RecursiveTools       example_recluster         Success
  RecursiveTools       example_softdrop          Success
  RecursiveTools       example_advanced_usage    Success
  RecursiveTools       example_recursive_softdrop Failed (see difference file)
  RecursiveTools       example_bottomup_softdrop Success
  RecursiveTools       example_isd               Success
  Nsubjettiness        example_basic_usage       Success
  Nsubjettiness        example_advanced_usage    Success
  Nsubjettiness        example_v1p0p3            Success
  Nsubjettiness        example_advanced_usage_ee Failed (see difference file)

32 out of 37 tests passed

In directory ConstituentSubtractor/ checking the output of 'example_background_rescaling' using the input file
../data/Pythia-Zp2jets-lhc-pileup-1ev.dat and reference file example_background_rescaling.ref
ERROR: Outputs differ (output, stderr and diff available in
       example_background_rescaling.tmp_ref , example_background_rescaling.tmp_err and example_background_rescaling.diff)


In directory ConstituentSubtractor/ checking the output of 'example_whole_event_using_charged_info' using the input file
../data/Pythia-Zp2jets-lhc-pileup-1ev.dat and reference file example_whole_event_using_charged_info.ref
g++ -o example_basic_usage example_basic_usage.o -L. -lJetsWithoutJets -lm -Wl,-rpath,/home/spack/spack/opt/spack/linux-centos8-aarch64/gcc-8.4.1/fastjet-3.3.3-hm2yxti4u6lk3svbhoezwq5cbfmxeevx/lib -L/home/spack/spack/opt/spack/linux-centos8-aarch64/gcc-8.4.1/fastjet-3.3.3-hm2yxti4u6lk3svbhoezwq5cbfmxeevx/lib -lfastjettools -lfastjet -lm
ERROR: Outputs differ (output, stderr and diff available in
       example_whole_event_using_charged_info.tmp_ref , example_whole_event_using_charged_info.tmp_err and example_whole_event_using_charged_info.diff)

make[1]: Leaving directory '/tmp/root/spack-stage/spack-stage-fjcontrib-1.045-p3757gwycatauhvqg2vtcbbx5fmlgvwv/spack-src/ConstituentSubtractor'
g++ -o example_advanced_usage example_advanced_usage.o -L. -lJetsWithoutJets -lm -Wl,-rpath,/home/spack/spack/opt/spack/linux-centos8-aarch64/gcc-8.4.1/fastjet-3.3.3-hm2yxti4u6lk3svbhoezwq5cbfmxeevx/lib -L/home/spack/spack/opt/spack/linux-centos8-aarch64/gcc-8.4.1/fastjet-3.3.3-hm2yxti4u6lk3svbhoezwq5cbfmxeevx/lib -lfastjettools -lfastjet -lm
g++ -O3 -Wall -g -I/home/spack/spack/opt/spack/linux-centos8-aarch64/gcc-8.4.1/fastjet-3.3.3-hm2yxti4u6lk3svbhoezwq5cbfmxeevx/include   -c -o example_recluster.o example_recluster.cc<http://example_recluster.cc>
g++ -O3 -Wall -Woverloaded-virtual -g -Wunused-parameter -I/home/spack/spack/opt/spack/linux-centos8-aarch64/gcc-8.4.1/fastjet-3.3.3-hm2yxti4u6lk3svbhoezwq5cbfmxeevx/include   -c -o example_v1p0p3.o example_v1p0p3.cc<http://example_v1p0p3.cc>

In directory JetsWithoutJets/ checking the output of 'example_basic_usage' using the input file
../data/single-event.dat and reference file example_basic_usage.ref

In directory JetsWithoutJets/ checking the output of 'example_advanced_usage' using the input file
../data/single-event.dat and reference file example_advanced_usage.ref
g++ -O3 -Wall -g -I/home/spack/spack/opt/spack/linux-centos8-aarch64/gcc-8.4.1/fastjet-3.3.3-hm2yxti4u6lk3svbhoezwq5cbfmxeevx/include   -c -o example_softdrop.o example_softdrop.cc<http://example_softdrop.cc>
ERROR: Outputs differ (output, stderr and diff available in
       example.tmp_ref , example.tmp_err and example.diff)

In directory RecursiveTools/ checking the output of 'example_recursive_softdrop' using the input file
../data/single-event.dat and reference file example_recursive_softdrop.ref
ERROR: Outputs differ (output, stderr and diff available in
       example_recursive_softdrop.tmp_ref , example_recursive_softdrop.tmp_err and example_recursive_softdrop.diff)

In directory Nsubjettiness/ checking the output of 'example_advanced_usage_ee' using the input file
../data/single-ee-event.dat and reference file example_advanced_usage_ee.ref
ERROR: Outputs differ (output, stderr and diff available in
       example_advanced_usage_ee.tmp_ref , example_advanced_usage_ee.tmp_err and example_advanced_usage_ee.diff)

Can you help me look at it?

Information on your system

***@***.*** spack-src]# spack debug report

  *   Spack: 0.16.1-1624-a0b5dcca3c
  *   Python: 3.6.8
  *   Platform: linux-centos8-aarch64
  *   Concretizer: original
