### ISSUE TITLE
Missing Shared Object Name

### ISSUE THREAD

**Issue by APN-Pucky** [fjcontrib/fjcontrib#4]
Gentoo QA complains about missing shared object name https://dev.gentoo.org/~zmedico/portage/doc/ch07s04.html.

Currently I patch it via

```diff
--- a/Makefile.in
+++ b/Makefile.in
@@ -54,7 +54,7 @@
 
 fragile_SHARED_SRC_LIST=@FRAGILE_SHARED_SRC_LIST@
 libfastjetcontribfragile.@DYNLIBEXT@: $(fragile_SHARED_SRC_LIST)
-	$(CXX) @DYNLIBOPT@ -fPIC -DPIC $(CXXFLAGS) `$(FASTJETCONFIG) --cxxflags --libs` $(fragile_SHARED_SRC_LIST) -o libfastjetcontribfragile.@DYNLIBEXT@
+	$(CXX) @DYNLIBOPT@ -fPIC -DPIC -Wl,-Ol -Wl,--as-needed -Wl,-soname,fastjetcontribfragile.so.0 $(LDFLAGS) $(CXXFLAGS) `$(FASTJETCONFIG) --cxxflags --libs` $(fragile_SHARED_SRC_LIST) -o libfastjetcontribfragile.@DYNLIBEXT@
 
 fragile-shared-install: fragile-shared
 	utils/install-sh -c -m 755 libfastjetcontribfragile.@DYNLIBEXT@ $(PREFIX)/lib
```

but I'd prefer a upstream solution. I can draft a PR, but again this seems to be only a mirror.

**Comment by gavinsalam** [comment]
Hi Alexander,

This breaks compilation on MacOS systems. I’m not sure if that’s because it’s a BSD system, or because of the use of clang as the default compiler (I suspect the former, because with clang on linux, things worked). Do you have any insight into that?

One possible solution (to be tested) might be to try changing the line


    dynlibopt="-shared"

to

    dynlibopt=“-shared -Wl,-Ol -Wl,--as-needed -Wl,-soname,fastjetcontribfragile.so<http://fastjetcontribfragile.so/>.0"

in the configure script.

Btw, what does "-Ol” do? Should it have been "-O1” (with the letter l [ell] replaced with the number 1)?

Another possibility is that we make a change so that users can select what dynlibopt they want to use at configure time.

Best,
Gavin


On 20 Oct 2024, at 12:14, Alexander Puck Neuwirth ***@***.***> wrote:



Gentoo QA complains about missing shared object name https://dev.gentoo.org/~zmedico/portage/doc/ch07s04.html.

Currently I patch it via

--- a/Makefile.in
+++ b/Makefile.in
@@ -54,7 +54,7 @@

 ***@***.***_SHARED_SRC_LIST@
 ***@***.***@: $(fragile_SHARED_SRC_LIST)
-       $(CXX) @DYNLIBOPT@ -fPIC -DPIC $(CXXFLAGS) `$(FASTJETCONFIG) --cxxflags --libs` $(fragile_SHARED_SRC_LIST) -o ***@***.***@
+       $(CXX) @DYNLIBOPT@ -fPIC -DPIC -Wl,-Ol -Wl,--as-needed -Wl,-soname,fastjetcontribfragile.so.0 $(LDFLAGS) $(CXXFLAGS) `$(FASTJETCONFIG) --cxxflags --libs` $(fragile_SHARED_SRC_LIST) -o ***@***.***@

 fragile-shared-install: fragile-shared
        utils/install-sh -c -m 755 ***@***.***@ $(PREFIX)/lib

but I'd prefer a upstream solution.

**Comment by APN-Pucky** [comment]
I am not familiar with MacOS, but it seems it uses `-Wl,-install_name` instead of `-Wl,-soname` for the linking (https://stackoverflow.com/a/8424297). Gentoo's CI also occasionally runs LLVM/clang on linux.

I think `-Ol` is a typo and was intended as `-O1`. Since it worked with `-Ol` I guess `-O1` is not needed either.

Usually we'd add it to LDFLAGS, but that would probably conflict with the subpackages. `dynlibopt` sounds good to me.

**Comment by gavinsalam** [comment]
Thanks. I’ve put in the modification Linux in the svn (and git mirror), but have left out the corresponding MacOS change (if someone requests this explicitly on MacOS, we can reconsider. It will go out together with the next release.


On 20 Oct 2024, at 13:04, Alexander Puck Neuwirth ***@***.***> wrote:



I am not familiar with MacOS, but it seems it uses -Wl,-install_name instead of -Wl,-soname for the linking (https://stackoverflow.com/a/8424297). Gentoo's CI also occasionally runs LLVM/clang on linux.

I think -Ol is a typo and was intended as -O1. Since it worked with -Ol I guess -O1 is not needed either.

Usually we'd add it to LDFLAGS, but that would probably conflict with the subpackages. dynlibopt sounds good to me.

**Comment by APN-Pucky** [comment]
My response is a bit late but: Thanks!

**Comment by matthewfeickert** [comment]
Somewhat related, for packaging on conda-forge for Apple silicon macOS builds, which (currently: 2024-12-14) use:

```yaml
MACOSX_DEPLOYMENT_TARGET:
- '11.0'
MACOSX_SDK_VERSION:
- '11.0'
c_stdlib:
- macosx_deployment_target
c_stdlib_version:
- '11.0'
channel_sources:
- conda-forge
channel_targets:
- conda-forge main
curl:
- '8'
cxx_compiler:
- clangxx
cxx_compiler_version:
- '18'
macos_machine:
- arm64-apple-darwin20.0.0
target_platform:
- osx-arm64
```

we needed to [patch](https://github.com/conda-forge/fastjet-contrib-feedstock/blob/6895f2a83147b970a4ce06f0ec495b9f57659de2/recipe/use-headerpad_max_install_names-linker-option.patch) in the `-headerpad_max_install_names` linker option for those macOS arm64 builds (https://github.com/conda-forge/fastjet-contrib-feedstock/pull/1)

```diff
--- a/Makefile.in
+++ b/Makefile.in
@@ -55,7 +55,7 @@ fragile-shared: libfastjetcontribfragile.@DYNLIBEXT@
 
 fragile_SHARED_SRC_LIST=@FRAGILE_SHARED_SRC_LIST@
 libfastjetcontribfragile.@DYNLIBEXT@: $(fragile_SHARED_SRC_LIST)
-       $(CXX) @DYNLIBOPT@ -fPIC -DPIC $(CXXFLAGS) `$(FASTJETCONFIG) --cxxflags --libs` $(fragile_SHARED_SRC_LIST) -o libfastjetcontribfragile.@DYNLIBEXT@
+       $(CXX) @DYNLIBOPT@ -fPIC -DPIC $(CXXFLAGS) -Wl,-headerpad_max_install_names `$(FASTJETCONFIG) --cxxflags --libs` $(fragile_SHARED_SRC_LIST) -o libfastjetcontribfragile.@DYNLIBEXT@
 
 fragile-shared-install: fragile-shared
        utils/install-sh -c -m 755 libfastjetcontribfragile.@DYNLIBEXT@ $(PREFIX)/lib
```

> I’ve put in the modification Linux in the svn (and git mirror), but have left out the corresponding MacOS change (if someone requests this explicitly on MacOS, we can reconsider. It will go out together with the next release.

@gavinsalam just to check, that release isn't out yet, as `fjcontrib-1.056` was released on 2024-10-07 and you posted on 2024-10-20, correct? To be clear that's not an issue in any way, I just wanted to verify that we have the correct latest release.

**Comment by gavinsalam** [comment]
The linux change was included as part of 1.100, released [yesterday](https://phab.hepforge.org/source/fastjetsvn/browse/contrib/tags/1.100/NEWS?as=source&blame=off). (That's not yet reflected in https://fastjet.hepforge.org/contrib/, which for reasons beyond our control is slow to update)

Do you know how -headerpad_max_install_names behaves on Intel Macs? That's in terms of being careful not to put in something that would break builds on those systems.

**Comment by matthewfeickert** [comment]
> The linux change was included as part of 1.100, released [yesterday](https://phab.hepforge.org/source/fastjetsvn/browse/contrib/tags/1.100/NEWS?as=source&blame=off).

Great, and thanks!

Aside: What's the best way to think about the `fastjet-contrib` tag structure? Does going from [`1.056`](https://phab.hepforge.org/source/fastjetsvn/browse/contrib/tags/1.056/) to [`1.100`](https://phab.hepforge.org/source/fastjetsvn/browse/contrib/tags/1.100/) mean something similar to going from `v0.5.6` to `v1.0.0` in SemVer?

> Do you know how -headerpad_max_install_names behaves on Intel Macs?

@gavinsalam No, but I can check later. I only applied [the patch](https://github.com/conda-forge/fastjet-contrib-feedstock/blob/6895f2a83147b970a4ce06f0ec495b9f57659de2/recipe/use-headerpad_max_install_names-linker-option.patch) to macOS arm64 builds as those were the only ones that needed it, but I can verify which linker options exist across macOS platforms. 

>  That's in terms of being careful not to put in something that would break builds on those systems.

Yeah, I very much understand and appreciate this view. :+1: I know how to do OS and platform guarding in CMake, but not what patterns reliably work in Make, but if we can find something reasonable I'm happy to submit patches.

**Comment by matthewfeickert** [comment]
@gavinsalam With [the patch](https://github.com/conda-forge/fastjet-contrib-feedstock/blob/6895f2a83147b970a4ce06f0ec495b9f57659de2/recipe/use-headerpad_max_install_names-linker-option.patch) applied, both x86 and arm64 macOS builds pass on conda-forge (c.f. https://github.com/conda-forge/fastjet-contrib-feedstock/pull/4/commits/4a25ace5d4500f7327ac81b89c4931d0d2495d78)

![image](https://github.com/user-attachments/assets/cba7e374-5a09-43a5-bb20-4dbd7337d9b8)

**Comment by gavinsalam** [comment]
I’ve put a version of this into our svn (and propagated to git), but in the configure file rather than the Makefile.in


--- a/configure

+++ b/configure

@@ -345,7 +345,11 @@ done

 escaped_srclist="$(echo ${srclist} | sed -e 's/[\/&]/\\&/g')"

 escaped_fragile_include="$(echo ${fragile_include} | sed -e 's/[\/&]/\\&/g')"

 if [ "x"`uname` == "xDarwin" ] ;  then

-    dynlibopt="-dynamiclib"

+    # -Wl,-headerpad_max_install_names requested at

+    # https://github.com/conda-forge/fastjet-contrib-feedstock/commit/4a25ace5d4500f7327ac81b89c4931d0d2495d78

+    # and checked by Matthew Feickert on MacOS x86 and arm64

+    # (makes it possible for install_name_tool to alter the load commands later)

+    dynlibopt="-dynamiclib -Wl,-headerpad_max_install_names"

     dynlibext="dylib"

     dynlibpostproc="install_name_tool -id \\1 \\1"

 else

On 15 Dec 2024, at 03:01, Matthew Feickert ***@***.***> wrote:



@gavinsalam<https://github.com/gavinsalam> With the patch<https://github.com/conda-forge/fastjet-contrib-feedstock/blob/6895f2a83147b970a4ce06f0ec495b9f57659de2/recipe/use-headerpad_max_install_names-linker-option.patch> applied, both x86 and arm64 macOS builds pass on conda-forge (c.f. ***@***.***<https://github.com/conda-forge/fastjet-contrib-feedstock/commit/4a25ace5d4500f7327ac81b89c4931d0d2495d78>)

image.png (view on web)<https://github.com/user-attachments/assets/cba7e374-5a09-43a5-bb20-4dbd7337d9b8>

**Comment by gavinsalam** [comment]
It should go into our 1.101 release

**Comment by gavinsalam** [comment]
> Aside: What's the best way to think about the fastjet-contrib tag structure? Does going from [1.056](https://phab.hepforge.org/source/fastjetsvn/browse/contrib/tags/1.056/) to [1.100](https://phab.hepforge.org/source/fastjetsvn/browse/contrib/tags/1.100/) mean something similar to going from v0.5.6 to v1.0.0 in SemVer?

SemVer is not obvious here because the version number increments not just for the fjcontrib framework, but also for changes to individual contribs + new contribs. That's the reason why we chose a different numbering format (x.yyy rather than x.y.z). But if one really needs to make a comparison, this is probably  closer to a 0.1.0 increase rather than a 1.0.0 one.

**Comment by matthewfeickert** [comment]
> I’ve put a version of this into our svn (and propagated to git), but in the configure file rather than the Makefile.in. It should go into our 1.101 release

Thanks very much, @gavinsalam!

**Comment by matthewfeickert** [comment]
```console
$ grep -r "fastjetcontribfragile.so.0" fjcontrib-1.100/
fjcontrib-1.100/configure:    dynlibopt="-shared -Wl,--as-needed -Wl,-soname,fastjetcontribfragile.so.0"
```

@APN-Pucky This hardocdes in Linux specific filenames, which is not good, as now all macOS builds need to be patched, and also this breaks other Linux builds. Why does Gentoo need this specifically?

**Comment by matthewfeickert** [comment]
@APN-Pucky

```bash
if [ "x"`uname` == "xDarwin" ] ;  then
    dynlibopt="-dynamiclib"
    dynlibext="dylib"
    dynlibpostproc="install_name_tool -id \\1 \\1"
else
    #dynlibopt="-shared"
    # the following more elaborate set of options requested by Alexander Puck Neuwirth
    # for compatibility with gentoo, cf. https://github.com/fjcontrib/fjcontrib/issues/4
    dynlibopt="-shared -Wl,--as-needed -Wl,-soname,fastjetcontribfragile.so.0"
    dynlibext="so"
    dynlibpostproc="" # some dummy command needed
fi
```

is breaking other Linux builds. Why does Gentoo need this specifically?

**Comment by APN-Pucky** [comment]
> is breaking other Linux builds.

in what way (I presume you mean the `--as-needed`)? Is it `clang` too? I thought it is only mac from https://github.com/APN-Pucky/mpfun90/commit/d00bfe06b8f69329464906817f7f8b795bed5388#commitcomment-149958290. I don't understand/see why/how it could break something.

> Why does Gentoo need this specifically?

Distros have been using that by default for about 15 years.
Gentoo sets it by default in `LDFLAGS` as it speeds up load times and simplifies reverse dependencies. Maybe `dynlibopt` should contain/copy the generic `LDFLAGS` instead of adding `--as-needed` manually? (https://wiki.gentoo.org/wiki/Project:Quality_Assurance/As-needed)


PS: The macos/darwin equivalent would be `-Wl,-dead_strip_dylibs` (as per https://github.com/gentoo/gentoo/blob/3de0dcbdd0c8680b553abd6c13e084e8640867d4/profiles/prefix/darwin/macos/features/clang-lld/make.defaults#L9)

**Comment by matthewfeickert** [comment]
(Sorry for the months delay &mdash; missed the reply 😬)

> in what way (I presume you mean the `--as-needed`)? Is it `clang` too? I thought it is only mac from [APN-Pucky/mpfun90@d00bfe0#commitcomment-149958290](https://github.com/APN-Pucky/mpfun90/commit/d00bfe06b8f69329464906817f7f8b795bed5388#commitcomment-149958290). I don't understand/see why/how it could break something.

No, I mean

```
-Wl,-soname,fastjetcontribfragile.so.0
```

It breaks everything at runtime with

```
error while loading shared libraries: fastjetcontribfragile.so.0: cannot open shared object file: No such file or directory
```

(example: The [Centauro `example.cc`](https://phab.hepforge.org/source/fastjetsvn/browse/contrib/contribs/Centauro/tags/1.0.0/example.cc) when [built and tested like so](https://github.com/conda-forge/fastjet-contrib-feedstock/blob/d9e7dfc837fe39fbd272f90b7ada253e073f8589/recipe/run_test_shared.sh#L79-L88) for conda-forge.)

I had to patch it out to restore working conda-forge builds with https://github.com/conda-forge/fastjet-contrib-feedstock/blob/d9e7dfc837fe39fbd272f90b7ada253e073f8589/recipe/remove-soname-flag-for-fastjetcontribfragile.patch in https://github.com/conda-forge/fastjet-contrib-feedstock/pull/5. As @wdconinc mentioned in Issue https://github.com/fjcontrib/fjcontrib/issues/5 it needs to get reverted or fixed.

**Comment by APN-Pucky** [comment]
> it needs to get reverted or fixed.

I agree that there should probably be a "lib" in front of the fastjetcontribfragile.so soname and want to apologize for the mess it created for some downstreams. I did not notice it since for Gentoo it is installed with various symlinks, since different codes (have) use(d) it with different names (as a result of the missing soname in the first place I guess?), i.e. [this](https://github.com/gentoo/gentoo/blob/cc597403231578f46143811e76287cb785275707/sci-physics/fastjet-contrib/fastjet-contrib-1.055.ebuild#L51) results in 
```
/usr/lib64/fastjetcontribfragile.so.0 -> libfastjetcontribfragile.so
/usr/lib64/libfastjetcontribfragile.so
/usr/lib64/libfastjetcontribfragile.so.0 -> libfastjetcontribfragile.so
```
on my system.

**Comment by matthewfeickert** [comment]
> want to apologize for the mess it created for some downstreams

no worries. It obviously hasn't been a big deal if people are only reporting it months later. We can figure this out. 👍 

@wdconinc and I can do local tests with patches applied but I think

```
dynlibopt="-shared -Wl,--as-needed -Wl,-soname,libfastjetcontribfragile.so.0"
```

like suggested in Issue https://github.com/fjcontrib/fjcontrib/issues/5 is also going to be problematic (my memory is that I already tried this in December 2024 and the same issues came up).

**Comment by matthewfeickert** [comment]
> I think
> 
> ```
> dynlibopt="-shared -Wl,--as-needed -Wl,-soname,libfastjetcontribfragile.so.0"
> ```
> 
> like suggested in Issue [#5](https://github.com/fjcontrib/fjcontrib/issues/5) is also going to be problematic (my memory is that I already tried this in December 2024 and the same issues came up).

Yes, that still gives

```
error while loading shared libraries: libfastjetcontribfragile.so.0: cannot open shared object file: No such file or directory
```

To give an explicit example with the suggested `-Wl,-soname,libfastjetcontribfragile.so.0` patch failing

```diff
diff --git a/configure b/configure
index 879d44f..47848de 100755
--- a/configure
+++ b/configure
@@ -352,7 +352,7 @@ else
     #dynlibopt="-shared"
     # the following more elaborate set of options requested by Alexander Puck Neuwirth
     # for compatibility with gentoo, cf. https://github.com/fjcontrib/fjcontrib/issues/4
-    dynlibopt="-shared -Wl,--as-needed -Wl,-soname,fastjetcontribfragile.so.0"
+    dynlibopt="-shared -Wl,--as-needed -Wl,-soname,libfastjetcontribfragile.so.0"
     dynlibext="so"
     dynlibpostproc="" # some dummy command needed
 fi
```

```bash
curl -sL https://fastjet.hepforge.org/contrib/downloads/fjcontrib-1.100.tar.gz | tar -xz
cd fjcontrib-1.100

cd Centauro
grep -rl '#include "Centauro.hh"' | xargs sed -i 's|#include "Centauro.hh"|#include "fastjet/contrib/Centauro.hh"|g'
$CXX example.cc -o example $CXXFLAGS $LDFLAGS -lfastjetcontribfragile -lfastjettools -lfastjet
./example < ../data/single-event.dat
```
```
./example: error while loading shared libraries: libfastjetcontribfragile.so.0: cannot open shared object file: No such file or directory
```

Where the local conda-forge package build of `libfastjetcontribfragile.so` has

```console
$ readelf -d $(find build_artifacts/pkg_cache/ -type f -iname libfastjetcontribfragile.so)

Dynamic section at offset 0x101768 contains 30 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libstdc++.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libgcc_s.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x000000000000000e (SONAME)             Library soname: [libfastjetcontribfragile.so.0]
 0x000000000000000f (RPATH)              Library rpath: [$ORIGIN/.]
 0x000000000000000c (INIT)               0x3c000
 0x000000000000000d (FINI)               0xd93d8
 0x0000000000000019 (INIT_ARRAY)         0xfe618
 0x000000000000001b (INIT_ARRAYSZ)       112 (bytes)
 0x000000000000001a (FINI_ARRAY)         0xfe688
 0x000000000000001c (FINI_ARRAYSZ)       8 (bytes)
 0x0000000000000004 (HASH)               0x200
 0x000000006ffffef5 (GNU_HASH)           0x3090
 0x0000000000000005 (STRTAB)             0x119f0
 0x0000000000000006 (SYMTAB)             0x6380
 0x000000000000000a (STRSZ)              114421 (bytes)
 0x000000000000000b (SYMENT)             24 (bytes)
 0x0000000000000003 (PLTGOT)             0x101fe8
 0x0000000000000002 (PLTRELSZ)           13080 (bytes)
 0x0000000000000014 (PLTREL)             RELA
 0x0000000000000017 (JMPREL)             0x382a0
 0x0000000000000007 (RELA)               0x2e970
 0x0000000000000008 (RELASZ)             39216 (bytes)
 0x0000000000000009 (RELAENT)            24 (bytes)
 0x000000006ffffffe (VERNEED)            0x2e820
 0x000000006fffffff (VERNEEDNUM)         4
 0x000000006ffffff0 (VERSYM)             0x2d8e6
 0x000000006ffffff9 (RELACOUNT)          16
 0x0000000000000000 (NULL)               0x0
$ ldd $(find build_artifacts/*/test_tmp/fjcontrib-1.100/Centauro/ -type f -iname example) | grep fastjet
	libfastjetcontribfragile.so.0 => not found
	libfastjettools.so.0 => not found
	libfastjet.so.0 => not found
```

**Comment by APN-Pucky** [comment]
> To give an explicit example with the suggested `-Wl,-soname,libfastjetcontribfragile.so.0` patch failing

What about dropping the `.0` suffix or symlinking the lib w/o `.0` and w/ `.0` (sort of like `ldconfig`)?

**Comment by matthewfeickert** [comment]
> What about dropping the `.0` suffix or symlinking the lib w/o `.0` and w/ `.0` (sort of like `ldconfig`)?

```
dynlibopt="-shared -Wl,--as-needed -Wl,-soname,libfastjetcontribfragile.so"
```

works (i.e. it builds and passes all the examples when using an installed conda package version). Does that work for you though @APN-Pucky and @wdconinc?

**Comment by APN-Pucky** [comment]
It works for me too. I thought that including a major version/ABI counter is common enough, e.g. all of
```bash
$ ls libzzipfseeko.so*
libzzipfseeko.so  libzzipfseeko.so.13  libzzipfseeko.so.13.0.78
```
have the soname `libzzipfseeko.so.13`.

**Comment by matthewfeickert** [comment]
> I thought that including a major version/ABI counter is common enough,

It is common and supported. There's problems in general with how fastjet-contrib builds `libfastjetcontribfragile` though it seems.
